trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'windows-latest'  # Use Windows agent for Playwright

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.cpsroj'
    arguments: 'dotnet build'
  displayName: 'Build project'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: '**/*.cpsroj'
    custom: 'pwsh bin/Debug/netX/playwright.ps1 install --with-deps'
  displayName: 'install playwright'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.cpsroj'
    feedsToUse: 'select'
  displayName: 'restore'
  condition: 
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.cpsroj'
    testRunTitle: 'Runnning PlayWright'
