name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to run tests'
        required: true
        default: 'SIT'
        type: choice
        options:
          - SIT
          - UAT
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0

    - name: Build & Install
      run: dotnet build

    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net6.0/playwright.ps1 install --with-deps

    # Clean up previous test and allure results before starting the tests
    - name: Clean Allure and Test Results
      run: |
        rm -rf allure-results
        rm -rf allure-report
        rm -rf test-results

    # Run the tests and generate Allure results directly
    - name: Run tests for ${{ github.event.inputs.environment }} environment
      env:
        TEST_ENV: ${{ github.event.inputs.environment }}
        TEST_URL: ${{ github.event.inputs.environment == 'SIT' && 'https://demoqa.com' || 'https://UAT-demoqa.com' }}  # Set the URL based on the environment
      run: |
        dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory test-results --filter "Category=${{ github.event.inputs.environment }}"
      continue-on-error: true

    # Capture failed screenshots as artifacts
    - name: Upload failed screenshots
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: failed-screenshots
        path: bin/Debug/net6.0/screenshots # Adjust this path based on where screenshots are stored

    # Install Allure CLI for generating the report
    - name: Install Allure CLI
      run: |
        npm install -g allure-commandline --save-dev

    # Generate the Allure report using the Allure results
    - name: Generate Allure report
      run: |
        allure generate --single-file --clean -o allure-report

    # Upload Allure report as artifact
    - name: Upload Allure report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
