name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0

    - name: Build & Install
      run: dotnet build

    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net6.0/playwright.ps1 install --with-deps

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    # Ensure that old Allure results are cleaned up
    - name: Clean Allure results
      run: rm -rf allure-results

    # Run tests and generate Allure results
    - name: Run tests with Allure
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory test-results -- NUnit.Allure

    # Generate Allure report
    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    # Upload Allure report as an artifact
    - name: Upload Allure report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
